spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dubbo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis-plus:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mapper/*.xml
  global-config:
      db-config:
        id-type: auto

#*****************分割线, 上面我就不解释了, 下面是dubbo的配置************************
dubbo:
  application:
    name: dubbo-producer  #dubbo的注册的服务名, 唯一性
  registry:
    address: zookeeper://47.105.200.53:2181  #注册zookeeper的地址
